dataset_yaml: "VTSDB100/data.yaml"
epochs: 50
batch_size: 16
val_batch_size: 8
imgsz: 640
device: ['0']
workers: 0
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 30
experiments_root: "full_experiments/vtsdb100_ppal_maple"
proctitle_midstr: "vtsdb100_ppal_maple"
proctitle_endstr_of: "seed"
seed: 1
strategy: ["dcus", "maple"]
expand_ratios: [2.0]
model_name: "yolo11n.pt"
initial_labeled_count: 15499 # 20% of 77499 train images, rounded down
max_rounds: 8
samples_per_round: 3875 # 5% of 77499 train images, rounded down
num_inference: -1

strategy_args:
  dcus:
    momentum: 0.99
    xi: 0.6
    alpha: 0.2
    beta: 0.2

  maple:
    maple_checkpoint_pattern: "{experiment_dir}/maple_checkpoints/round_{round:03d}.pt"
    maple_checkpoint_fallback_latest: False
    maple_weight: 1.0
    entropy_weight: 1.0
    disagreement_weight: 1.0
    inverse_confidence_weight: 0.0
    yolo_confidence_weight: 0.0
    padding: 0.15
    batch_size: 8
    maple_device: "cuda:0"

maple_training:
  enabled: True
  crop_dirname: "maple_crops"
  backbone: "ViT-B/16"
  n_ctx: 2
  ctx_init: ""
  prompt_depth: 9
  epochs: 10
  batch_size: 8
  num_workers: 4
  learning_rate: 0.0025
  weight_decay: 0.0005
  momentum: 0.9
  device: "cuda:0"
  padding: 0.15
