dataset_yaml: "VTSDB100/data.yaml"
epochs: 20
batch_size: 48
val_batch_size: 8
imgsz: 640
device: ['0']
workers: 4
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 30
experiments_root: "full_experiments/vtsdb100_random"
proctitle_midstr: "vtsdb100_random"
proctitle_endstr_of: "seed"
seed: 1
strategy: "random"
model_name: "yolo11n.pt"
initial_labeled_count: 15499 # 20% of 77499 train images, rounded down
max_rounds: 6
samples_per_round: 3875 # 5% of 77499 train images, rounded down
num_inference: -1
